[default]
mode=mcts
active-heuristics=mcts-edsm, greedy-edsm

[mcts]
mcts-heuristic=mcts-edsm
comparison-heuristic=greedy-edsm

valuation-policy=norm-rollout-length(minimise)

selection-search-policy=best-child-vs-parent
node-selection-policy=lcb1
lcb1-constant=0.00601556971

convergence-policies=node-termination,score-improvement
max-no-improvement=-1

rollout-action-policy=uniform
rollout-weighted-extend-scoring=min
rollout-action-seed=96466
max-rollout-steps=-1

expansion-action-policy=greedy
expansion-action-seed=42
auto-expand-one-child=1

use-finisher=0
force-until-terminal=0

store-rollouts=1
print-unvisited=1

[heuristic]
name = greedy-edsm
heuristic-name = evidence_driven
data-name = edsm_data
sinkson = 0
sinkcount = 0
state_count = 0
symbol_count = 0
lowerbound = 0
extend = 0
extendsinks=1
largestblue = 0
blueblue=0
redfixed=0
allfixed=0

[heuristic]
name = mcts-edsm
heuristic-name = evidence_driven
data-name = edsm_data
sinkson = 0
sinkcount = 0
state_count = 0
symbol_count = 0
lowerbound = 0
extend=0
; Used for the property that all extends will be searched
extendsinks=1
; Used such that the property only largest blue is checked is turned off, so it returns all information, to be
; able to generate sub trees
largestblue = 0

blueblue=0
redfixed=0
allfixed=0

