[default]
mode=mcts
active-heuristics=mcts-edsm, greedy-edsm

[mcts]
valuation-policy=model-size
selection-policy=lcb1
max-rollout-steps=-1
convergence-policies=node-termination
max-no-improvement=5000
force-until-terminal=0
rollout-action-policy=weighted
rollout-weighted-extend-scoring=max
rollout-action-seed=42
expansion-action-policy=greedy
expansion-action-seed=42
selection-search-policy=best-child-vs-parent
auto-expand-one-child=1
use-finisher=0
mcts-heuristic=mcts-edsm
comparison-heuristic=greedy-edsm

[[heuristic]]
name = greedy-edsm
heuristic-name = evidence_driven
data-name = edsm_data
sinkson = 0
lowerbound = 0
printwhite = 0
extend = 0
largestblue = 1

[[heuristic]]
name = mcts-edsm
heuristic-name = evidence_driven
data-name = edsm_data
sinkson = 0
sinkcount = 10
state_count = 0
symbol_count = 0
lowerbound = 0
extend=0
; Used for the property that all extends will be searched
extendsinks=1
; Used such that the property only largest blue is checked is turned off, so it returns all information, to be
; able to generate sub trees
largestblue = 0
blueblue=0
redfixed=0
allfixed=0


[[heuristic]]
name = mcts-aic
heuristic-name = aic
data-name = aic_data
state_count = 0
symbol_count = 0
sinkson = 0
sinkcount = 0
correction = 0
finalprob=1
; Used for the property that all extends will be searched
extend=0
; Used such that the property only largest blue is checked is turned off, so it returns all information, to be
; able to generate sub trees
largestblue = 0
blueblue=0
redfixed=0
allfixed=0

[[heuristic]]
name = mcts-overlap
heuristic-name = overlap_driven
data-name = overlap_data
sinkson = 0
sinkcount = 10
state_count = 10
symbol_count = 0
lowerbound = 1
markovian = 0
mcollector = 3
mergelocal = 3
; Used for the property that all extends will be searched
extend=0
; Used such that the property only largest blue is checked is turned off, so it returns all information, to be
; able to generate sub trees
largestblue = 0
blueblue=0
redfixed=0
allfixed=0

[[heuristic]]
name = greedy-alergia
heuristic-name = alergia
data-name = alergia_data
state_count = 0
symbol_count = 0
satdfabound = 2000
sinkson = 0
blueblue = 0
sinkcount = 4
extrapar = 0.0001
largestblue = 1
finalred = 0
lowerbound = 0
finalprob = 1
mergelocal = -1
mcollector = -1
markovian = 0
extend = 0

[[heuristic]]
name=mcts-alergia
heuristic-name = alergia
data-name = alergia_data
state_count = 0
symbol_count = 0
satdfabound = 2000
sinkson = 0
sinkcount = 4

; Used for the property that all extends will be searched
extend=0
; Used such that the property only largest blue is checked is turned off, so it returns all information, to be
; able to generate sub trees
largestblue = 0
blueblue = 0

extrapar = 0.0001
finalred = 0
lowerbound = 0
finalprob = 1
mergelocal = -1
mcollector = -1
markovian = 0
